spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: hggi
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
app:
  redis:
    timeoutSeconds: 60
    redisPort: 6379
    redisHost: localhost


